travis:
  secure:
    BINSTAR_TOKEN: rFadApXydwse4vgkX1yK1kp36OhAQgV5d5ZbkxyWCT1iDaL7VKFQ/c8ec1URGuUQV693JOvMQ+6agzO4yF9aYrgs/puUyqQKqhYoQ6wKshB7E8xIjx7Ha2Q8NwFPN8gKyGyO4x/2BO3v/TBiDMmZYc1jfh+WrUeAmYr/g0/RJHjhbg6ZL5vmqATGMdq+JHvhgGHBCWIwNUQ+Ke+uxRx3iMafuGIS3RLIHyVaiLlG2qgHft2oZGPgAVJexJUtC9K+5r1xq0LkB6mdZ5i8Dmz/lBea7S486IvjqSCcMfShqM0+4yYz3suTpXc1Y8g/ObGKUh5rp4XAH26qmLz/13d2PjnM3AB+zPS1ZEy0XCcsduFrgF4Yy+H2h7oNov1B/sQnHBsOPMKlINmqSp8MjFuELkb0eqtMDhva3AzSHMT9gvZdN/ggedMWJWjfjSWev6ilN7PB6k2cbDPw2DYJ1PwWADfve8SIxFngzGMtIQaDg/7Rc7o5BVvX7pzrUIguRqNsrS39zRJSOcTycjrHfNoKr58RlirCvsY7r/t3ybf3h+a4ukQJCx2Uz+Im4wwxVDihgpIioVeZ5a0tESBzTqTY7BY/ChCE/9esgDWRoqUNwXfLgW67XBsv5N3UW+MCunBIt2FgJZSo//MZ8AZQ5W//ZcBNIiY9kBgiuqLStUkgvkE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
